//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web;
    public partial class AdminUser
    {
        [Key]
        public int ID { get; set; }
        [Required(ErrorMessage = "Tai khoan khong duoc de trong")]
        [DisplayName("Tài kho?n")]
        public string NameUser { get; set; }
        public string RoleUser { get; set; }
        [Required(ErrorMessage = "Mat khau khong duoc de trong")]
        [DisplayName("M?t kh?u")]
        public string PasswordUser { get; set; }
    }
}
