//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
        [Key]
        public int IDCus { get; set; }
        [Required(ErrorMessage = "Tai khoan khong duoc de trong")]
        [DisplayName("Tài kho?n")]
        [StringLength(50, MinimumLength = 6)]
        public string NameCus { get; set; }
        public string PhoneCus { get; set; }
        [Required(ErrorMessage = "Email khong duoc de trong")]
        [DisplayName("Email")]
        public string EmailCus { get; set; }
        [Required(ErrorMessage = "Mat khau khong duoc de trong")]
        [DisplayName("M?t kh?u")]
        [DataType(DataType.Password)]
        [StringLength(50, MinimumLength = 6)]
        public string PassCus { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
